version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "20:00"
      timezone: Israel
    ignore:
      - dependency-name: "@yoavain*"
    open-pull-requests-limit: 10
